#!/usr/bin/env bash
#
# Take the store screenshots, from the running app.
#
# The shots have to show real work — a mocked conversation looks like one, and
# the one thing a store listing has to establish is that the thing is real. So
# this drives the actual app against an actual harness.
#
# It will not use yours. A screenshot of a real machine is a screenshot of
# somebody's project paths, somebody's conversations, and somebody's hostname,
# and all three end up on a public page. Instead it starts a throwaway harness
# with its own DSH_HOME, its own port, and its own pairing identity, seeded with
# a sample repository, and pairs a simulator to that.
#
# Usage:
#   ios/screenshots.sh            set up if needed, then take them
#   ios/screenshots.sh --seed     set up and seed conversations, then stop
#   ios/screenshots.sh --shots    take them against an environment already up
#
# Requirements: xcodegen, a booted-able iPhone simulator, and dsh on the PATH.
# The sample harness borrows ~/.dsh/settings.yaml for model credentials — it
# needs a model to answer, and copying the file is the only way it gets one.

set -euo pipefail

cd "$(dirname "$0")"
root="$(cd .. && pwd)"
home="${ROWEL_SHOTS_HOME:-$HOME/rowel-shots}"
port="${ROWEL_SHOTS_PORT:-3082}"
device="${ROWEL_SHOTS_DEVICE:-iPhone 17 Pro Max}"
sample="$HOME/code/checkout-api"

if [ -t 1 ]; then bold=$(printf '\033[1m'); off=$(printf '\033[0m'); else bold=''; off=''; fi
say() { printf '%s==>%s %s\n' "$bold" "$off" "$*"; }
fail() { printf '%s\n' "$*" >&2; exit 1; }

command -v dsh >/dev/null 2>&1 || fail "dsh is not on the PATH."
command -v xcodegen >/dev/null 2>&1 || fail "xcodegen is not installed. brew install xcodegen"
[ -f "$root/bridle/lib/cli.js" ] || fail "The Bridle is not built. Run: npm run build"

rpc() {
  curl -s -m 90 -X POST "http://127.0.0.1:$port/api/$1" \
    -H 'content-type: application/json' \
    -d "{\"type\":\"client-request\",\"rpcId\":\"s$RANDOM\",\"method\":\"$1\",\"payload\":$2}"
}
value() { python3 -c 'import json,sys;print(json.load(sys.stdin)["result"]["value"]'"$1"')'; }

# --- A harness of its own ---------------------------------------------------

start_harness() {
  if curl -s -o /dev/null -m 2 "http://127.0.0.1:$port/"; then
    say "harness already up on :$port"
    return
  fi
  mkdir -p "$home/dsh-home/profiles/web"
  [ -f "$home/dsh-home/settings.yaml" ] || {
    [ -f "$HOME/.dsh/settings.yaml" ] || fail "no ~/.dsh/settings.yaml to borrow model credentials from."
    cp "$HOME/.dsh/settings.yaml" "$home/dsh-home/settings.yaml"
    chmod 600 "$home/dsh-home/settings.yaml"
  }
  # The port lives in the home's own config, which is what makes the home the
  # instance: a second dsh started here loses the port and stops, rather than
  # quietly becoming a second answer to the same question.
  cat > "$home/dsh-home/profiles/web/cordis.patch.yml" <<YAML
# Screenshot profile — regenerated by ios/screenshots.sh when missing.

- id: directory-picker
  disabled: true

- insert:
    - id: directory-picker-browse
      name: '@deepseek-ai/dsh-host-directory-picker-browse'

- id: llm-deepseek
  disabled: true

- id: webserver
  config:
    host: 127.0.0.1
    port: $port
YAML
  DSH_TELEMETRY_DISABLED=1 DSH_HOME="$home/dsh-home" nohup dsh web >> "$home/dsh.log" 2>&1 &
  printf 'harness starting on :%s ' "$port"
  until curl -s -o /dev/null -m 2 "http://127.0.0.1:$port/"; do printf '.'; sleep 1; done
  echo ' up'
}

start_bridle() {
  if [ -f "$home/rowel-home/runtime.json" ]; then
    pid="$(python3 -c "import json;print(json.load(open('$home/rowel-home/runtime.json'))['pid'])" 2>/dev/null || echo 0)"
    if [ "$pid" -gt 0 ] && kill -0 "$pid" 2>/dev/null; then
      say "bridle already running (pid $pid)"
      return
    fi
  fi
  ROWEL_HOME="$home/rowel-home" nohup node "$root/bridle/lib/cli.js" start \
    --dsh-home "$home/dsh-home" >> "$home/bridle.log" 2>&1 &
  sleep 6
  say "bridle up"
}

# --- A repository worth photographing ---------------------------------------

seed_repo() {
  mkdir -p "$sample"
  cat > "$sample/README.md" <<'EOF'
# checkout-api

Payment intents, refunds, and webhook delivery for the storefront.
EOF
  cat > "$sample/rates.py" <<'EOF'
"""Currency conversion for checkout totals."""

RATES = {"USD": 1.0, "EUR": 0.92, "GBP": 0.79, "JPY": 157.0}


def convert(amount, source, target):
    """Convert an amount between two supported currencies."""
    return amount / RATES[source] * RATES[target]


def total_with_shipping(items, currency, shipping=0):
    subtotal = sum(item["price"] for item in items)
    return convert(subtotal + shipping, "USD", currency)
EOF
  cat > "$sample/test_rates.py" <<'EOF'
from rates import convert, total_with_shipping


def test_same_currency_is_identity():
    assert convert(10, "USD", "USD") == 10


def test_round_trip():
    assert round(convert(convert(10, "USD", "EUR"), "EUR", "USD"), 6) == 10
EOF
  python3 - "$sample" <<'EOF'
import json, random, sys
random.seed(7)
days = [{"date": f"2026-08-{i + 1:02d}",
         "orders": random.randint(80, 260),
         "refunds": random.randint(0, 14),
         "revenue": round(random.uniform(4200, 15800), 2),
         "p95_checkout_ms": random.randint(180, 900)} for i in range(30)]
json.dump({"currency": "USD", "days": days},
          open(f"{sys.argv[1]}/metrics.json", "w"), indent=2)
EOF
  say "sample repository seeded at $sample"
}

# --- Conversations the shots are of -----------------------------------------

converse() { # title, prompt
  local sid
  sid=$(rpc session.create "{\"cwd\":\"$sample\"}" | value '["sessionId"]')
  rpc session.prompt "{\"sessionId\":\"$sid\",\"mode\":\"queue\",\"content\":[{\"type\":\"text\",\"text\":\"$2\"}],\"clientTimeZone\":\"$(date +%Z)\"}" >/dev/null
  sleep 1
  rpc session.rename "{\"sessionId\":\"$sid\",\"title\":\"$1\"}" >/dev/null
  say "  $1"
}

seed_conversations() {
  local wid
  wid=$(rpc workspace.create "{\"path\":\"$sample\"}" | value '["workspace"]["workspaceId"]' 2>/dev/null || true)
  [ -n "$wid" ] && rpc workspace.rename "{\"workspaceId\":\"$wid\",\"title\":\"checkout-api\"}" >/dev/null
  say "starting conversations"
  converse "Add CAD and AUD to the currency table" \
    "Read rates.py and test_rates.py, then add CAD and AUD with correct rates and a test for each. Run the tests when you are done."
  converse "Why does the webhook retry twice?" \
    "Read README.md and explain in two sentences what this service is for."
  converse "Build the checkout health dashboard" \
    "Plan this out with a todo list first, then do it. Read metrics.json, work out the trends that matter, and build dashboard.html: a single self-contained dark-mode page with inline SVG charts and a verdict banner. No external assets. Check it renders, then tell me what the data says."
  # The one that has to stop and ask. The remote does not exist, on purpose.
  converse "Ship the currency fix" \
    "Initialise a git repo here, commit everything with the message 'Add CAD and AUD support', then push it to the remote at git@github.com:example/checkout-api.git"
  say "give them a few minutes to finish before taking the shots"
}

# --- The shots --------------------------------------------------------------

take() {
  local udid
  udid=$(xcrun simctl list devices available | grep -m1 "$device (" | sed -E 's/.*\(([0-9A-F-]{36})\).*/\1/')
  [ -n "$udid" ] || fail "no simulator called '$device'."
  xcrun simctl boot "$udid" 2>/dev/null || true
  open -a Simulator

  # A sketch to attach, so the photo shot has something to be of.
  [ -f /tmp/rowel-sketch.png ] || swift Tools/Sketch.swift /tmp/rowel-sketch.png
  xcrun simctl addmedia "$udid" /tmp/rowel-sketch.png 2>/dev/null || true

  xcodegen generate --spec project.yml >/dev/null

  # Hand the run a fresh invitation rather than telling the operator to pair by
  # hand and carrying on either way. A stale pairing does not announce itself —
  # the app simply never reaches the machine — and the shots that come out of a
  # run like that are of an app with nothing in it, which is exactly the failure
  # this whole file exists to avoid.
  #
  # `TEST_RUNNER_` is not decoration: xcodebuild passes the test process only
  # variables with that prefix, and strips it on the way through.
  local link
  link=$(ROWEL_HOME="$home/rowel-home" node "$root/bridle/lib/cli.js" pair --link 2>/dev/null \
    | sed -n 's/^link: *//p')
  [ -n "$link" ] || fail "could not mint a pairing invitation for $home/rowel-home"
  export TEST_RUNNER_ROWEL_PAIR_LINK="$link"

  xcodebuild test -project Rowel.xcodeproj -scheme RowelUI \
    -destination "id=$udid" -only-testing:RowelUITests/Screenshots \
    | grep -E "Test Case|error:" || true

  # The artifact the dashboard conversation built, rendered.
  chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  if [ -x "$chrome" ] && [ -f "$sample/dashboard.html" ]; then
    "$chrome" --headless --disable-gpu --hide-scrollbars --window-size=1600,1200 \
      --screenshot="$root/marketing/shots/dashboard.png" \
      "file://$sample/dashboard.html" >/dev/null 2>&1
    # Crop from the top, not the middle. `sips -c` centres, which sliced the
    # headings off the three summary cards and left their explanatory text
    # floating above the chart — the one image on the page that is supposed to
    # show what the agent produced, looking like a layout that had gone wrong.
    # 860 is where the page's own content ends.
    magick "$root/marketing/shots/dashboard.png" -crop 1600x860+0+0 +repage \
      "$root/marketing/shots/dashboard.png"
  fi

  # Web copies, small enough for a page to carry.
  #
  # `--resampleWidth`, not `-Z`. `-Z` caps the *longest* edge, and these are
  # portrait, so it set the height to 660 and left the width at 303 — under
  # half of what the page needs. The slot is 13.5rem (216 CSS px) and a phone
  # renders it at 3×, so 660 wide is the number; 303 was visibly soft on every
  # retina screen while the README claimed 660 the whole time.
  #
  # WebP, because the page is nothing but screenshots and one of them is a
  # notification over a photograph, which PNG cannot compress: the set was
  # 2.1 MB as PNG and is 400 KB as WebP at the same pixels. The page references
  # `.webp` directly rather than through a `<picture>` fallback — every browser
  # that can run the app's own marketing has supported it for years, and a
  # second copy of every image is a second thing to keep in step.
  command -v cwebp >/dev/null \
    || fail "cwebp is not installed, and the site references .webp — brew install webp"
  mkdir -p "$root/site/public/_/shots"
  local tmp="${TMPDIR:-/tmp}/rowel-web-shot.png"
  for n in sessions conversation approval photo models push pairing-sheet machine tools artifact; do
    cp "$root/marketing/shots/$n.png" "$tmp"
    sips --resampleWidth 660 "$tmp" >/dev/null
    cwebp -q 88 -quiet "$tmp" -o "$root/site/public/_/shots/$n.webp"
  done
  if [ -f "$root/marketing/shots/dashboard.png" ]; then
    cp "$root/marketing/shots/dashboard.png" "$tmp"
    # Landscape, so the longest edge is the width and `-Z` would be right here
    # too; spelled the same way as the others so the next reader does not have
    # to work out why one line differs.
    sips --resampleWidth 1200 "$tmp" >/dev/null
    cwebp -q 88 -quiet "$tmp" -o "$root/site/public/_/shots/dashboard.webp"
  fi
  rm -f "$tmp"
  say "shots in marketing/shots, web copies in site/public/_/shots"
}

case "${1:-}" in
  --seed) start_harness; start_bridle; seed_repo; seed_conversations ;;
  --shots) take ;;
  *) start_harness; start_bridle; seed_repo; seed_conversations; sleep 120; take ;;
esac
